# This is an example secrets file.
# 1. Rename this file to secrets.yaml
# 2. Replace the placeholder values below with your actual credentials.
# 3. Make sure secrets.yaml is NOT committed to version control (e.g., add it to .gitignore).

# Home Assistant API Encryption Key (Generate a strong random key)
# Example generation command: openssl rand -base64 32
api_key: "YOUR_STRONG_API_ENCRYPTION_KEY_HERE"

# Password for Over-The-Air (OTA) updates
ota_password: "YOUR_OTA_UPDATE_PASSWORD_HERE"

# Your Wi-Fi Network Credentials
wifi_ssid: "YourWiFiNetworkName"
wifi_password: "YourWiFiPassword"

# NTP Server for time synchronization (optional, defaults usually work)
# Find servers near you at https://www.ntppool.org/
ntp_server: "pool.ntp.org"

# Your local timezone (Find options at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
# Examples: "America/New_York", "Europe/London", "Asia/Tokyo"
timezone: "America/Los_Angeles" 